#!/usr/bin/env node
// Generate an OSCAL profile - your tailoring of a BSI catalog - from a small
// tailoring file.
//
// A Statement of Applicability says which requirements apply. As an OSCAL
// profile that selection becomes data other tools can read: the worksheet
// takes it with --profile, and a system security plan imports it later.
//
// Input (JSON):
//   {
//     "title": "Grundschutz++ tailoring of <organisation>",
//     "version": "2026-09-27",
//     "last-modified": "2026-09-27T00:00:00Z",
//     "catalog": { "path": "control_layer/.../...-resolved_catalog.json",
//                  "commit": "<40-char sha of the BSI library>" },
//     "applicable": ["DET.2.1", "KONF.3.2", ...],
//     "not-applicable": [{ "id": "ARCH.6.1", "reason": "no own WAN links" }, ...]
//   }
//
// Output: an OSCAL 1.1.3 profile on stdout (the version the library's own
// profiles use). It imports the catalog at the pinned commit and includes the
// applicable IDs. OSCAL profiles have no field for "excluded, and why", so the
// not-applicable requirements are recorded as back-matter resources with the
// reason, marked with this repository's namespace. The system security plan
// is where OSCAL expects that statement; until one exists, it stays here.
//
// Deterministic: UUIDs are derived from the content (v5-style), and
// last-modified comes from the input. The same input gives the same bytes, so a
// changed profile shows exactly the rows that changed.
//
// Every ID is checked against the catalog at the pinned commit. An unknown ID,
// an ID listed twice, or an ID that is both applicable and not applicable is
// an error - nothing is dropped silently.
//
//   node profile.mjs tailoring.json > profile.json
//
// No dependencies. Node 24 (LTS) or later.

import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";

const REPO = "https://raw.githubusercontent.com/BSI-Bund/Stand-der-Technik-Bibliothek";
const NS = "https://github.com/ohartwig/grundschutz-worksheets/ns";
// Fixed namespace for the derived UUIDs of this tool.
const UUID_NS = "b1f0c6a2-5d3e-4f7a-9c8b-2e6d1a4f0b37";

const file = process.argv[2];
if (!file) {
  console.error("usage: profile.mjs <tailoring.json>");
  process.exit(2);
}
const t = JSON.parse(readFileSync(file, "utf8"));
const fail = (msg) => {
  console.error(msg);
  process.exit(1);
};

if (!/^[0-9a-f]{40}$/.test(t.catalog?.commit ?? "")) fail("catalog.commit must be a 40-character commit");
for (const k of ["title", "version", "last-modified"]) if (!t[k]) fail(`missing "${k}"`);

// UUID v5 layout from a SHA-1 over namespace + name.
const uuid5 = (name) => {
  const ns = Buffer.from(UUID_NS.replace(/-/g, ""), "hex");
  const h = createHash("sha1").update(Buffer.concat([ns, Buffer.from(name, "utf8")])).digest();
  h[6] = (h[6] & 0x0f) | 0x50;
  h[8] = (h[8] & 0x3f) | 0x80;
  const x = h.subarray(0, 16).toString("hex");
  return `${x.slice(0, 8)}-${x.slice(8, 12)}-${x.slice(12, 16)}-${x.slice(16, 20)}-${x.slice(20)}`;
};

const href = `${REPO}/${t.catalog.commit}/${t.catalog.path.split("/").map(encodeURIComponent).join("/")}`;
const r = await fetch(href);
if (!r.ok) fail(`${r.status} for ${href}`);
const { catalog } = await r.json();
if (!catalog) fail("not an OSCAL catalog");

const known = new Set();
const walk = (controls) => {
  for (const c of controls ?? []) {
    known.add(c.id);
    walk(c.controls);
  }
};
const groups = (gs) => {
  for (const g of gs ?? []) {
    walk(g.controls);
    groups(g.groups);
  }
};
walk(catalog.controls);
groups(catalog.groups);

const byId = (a, b) => a.localeCompare(b, "en", { numeric: true });
const applicable = [...(t.applicable ?? [])];
const na = [...(t["not-applicable"] ?? [])];
const seen = new Map();
const errors = [];
for (const id of applicable) seen.set(id, (seen.get(id) ?? 0) + 1);
for (const e of na) {
  if (!e.reason) errors.push(`${e.id}: not-applicable without a reason`);
  seen.set(e.id, (seen.get(e.id) ?? 0) + 1);
}
for (const [id, n] of seen) {
  if (n > 1) errors.push(`${id}: listed ${n} times`);
  if (!known.has(id)) errors.push(`${id}: not in the catalog at ${t.catalog.commit.slice(0, 7)}`);
}
if (errors.length) fail(`${errors.length} error(s):\n  ${errors.join("\n  ")}`);

const profile = {
  profile: {
    uuid: uuid5(`profile:${t.title}:${t.catalog.path}`),
    metadata: {
      title: t.title,
      "last-modified": t["last-modified"],
      version: t.version,
      "oscal-version": "1.1.3",
      props: [
        { name: "catalog-commit", ns: NS, value: t.catalog.commit },
        { name: "applicable", ns: NS, value: String(applicable.length) },
        { name: "not-applicable", ns: NS, value: String(na.length) },
      ],
      remarks:
        "Generated by grundschutz-worksheets profile.mjs from a tailoring file. Do not edit by hand. " +
        "Requirements that do not apply are listed in back-matter with their reason.",
    },
    imports: [
      {
        href,
        "include-controls": [{ "with-child-controls": "no", "with-ids": applicable.sort(byId) }],
      },
    ],
    merge: { "as-is": true },
    ...(na.length && {
      "back-matter": {
        resources: na
          .sort((a, b) => byId(a.id, b.id))
          .map((e) => ({
            uuid: uuid5(`not-applicable:${e.id}`),
            title: `Not applicable: ${e.id}`,
            description: e.reason,
            props: [
              { name: "control-id", ns: NS, value: e.id },
              { name: "tailoring", ns: NS, value: "not-applicable" },
            ],
            // OSCAL requires a resource to carry its content (rlink or base64);
            // the JSON schema does not enforce it, the Metaschema constraints do.
            base64: {
              filename: `not-applicable-${e.id}.txt`,
              "media-type": "text/plain",
              value: Buffer.from(e.reason, "utf8").toString("base64"),
            },
          })),
      },
    }),
  },
};

process.stdout.write(JSON.stringify(profile, null, 2) + "\n");
